#!/usr/bin/env python3
"""
Populate content/moves/<slug>.md frontmatter + Description body from the
canonical move and ability data in the PokemonWorld repo.

Reads:
    PokemonWorld-master/pokemon-world-core/src/main/resources/data/moves.json
    PokemonWorld-master/pokemon-world-core/src/main/resources/data/abilities.json

For each move/ability, finds the matching content/moves/<slug>.md file
(generated by ingest_pokedex.py) and rewrites the frontmatter from the source
data. The "Description" section body is overwritten too. The
"Mechanics on Pokefind" section (and anything below it) is left intact, so
hand-written editorial notes survive re-runs.

Usage:
    python3 scripts/populate_moves.py [--moves PATH] [--abilities PATH]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MOVES_DIR = ROOT / "content/moves"

DEFAULT_MOVES = Path("/home/jack/ClaudeProjects/PokemonWorld-master/pokemon-world-core/src/main/resources/data/moves.json")
DEFAULT_ABILITIES = Path("/home/jack/ClaudeProjects/PokemonWorld-master/pokemon-world-core/src/main/resources/data/abilities.json")
DEFAULT_SPECIES = Path("/home/jack/Downloads/species_gen6.json")


def species_filtered(species: list[dict]) -> list[dict]:
    """Apply the same gen6/gen7/orphan-negative filter that ingest_pokedex.py
    uses, so move-page learner lists only reference species that actually have
    a Pokedex page."""
    REGIONAL_PREFIXES = {
        "Alolan", "Galarian", "Hisuian", "Paldean",
        "Kyoto", "Jataro", "Haikou", "Shiloh", "Zeinova",
    }
    out = []
    for s in species:
        sid = s.get("id")
        if isinstance(sid, int) and 650 <= sid <= 721:
            continue
        if isinstance(sid, int) and 722 <= sid <= 809:
            continue
        if isinstance(sid, int) and sid < 0:
            first = (s.get("name") or "").strip().split(" ", 1)[0]
            if first not in REGIONAL_PREFIXES:
                continue
        out.append(s)
    return out


def content_slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")


def detect_form(name: str) -> tuple[str, str]:
    REGIONAL_PREFIXES = [
        "Alolan", "Galarian", "Hisuian", "Paldean",
        "Kyoto", "Jataro", "Haikou", "Shiloh", "Zeinova",
    ]
    stripped = (name or "").strip()
    for prefix in REGIONAL_PREFIXES:
        token = prefix + " "
        if stripped.startswith(token):
            return (stripped[len(token):].strip(), prefix)
    return (stripped, "Standard")


def build_learners(species_list: list[dict]) -> tuple[dict, dict]:
    """Return (move_learners, ability_learners).
    move_learners: name -> {'level': [(species_label, level)], 'tm': [...], 'tutor': [...], 'egg': [...]}
    ability_learners: name -> [species_label, ...]
    species_label is the name as shown on the Pokedex (the form's full name)."""
    move_learners: dict[str, dict[str, list]] = {}
    ability_learners: dict[str, list[str]] = {}

    def note_move(move, species_label, source, level=None):
        bucket = move_learners.setdefault(move, {"level": [], "tm": [], "tutor": [], "egg": []})
        if source == "level":
            bucket["level"].append((species_label, level))
        else:
            bucket[source].append(species_label)

    def note_ability(ability, species_label):
        ability_learners.setdefault(ability, []).append(species_label)

    for s in species_list:
        full_name = s.get("name", "").strip()
        base_name, _ = detect_form(full_name)
        # Label uses the full name (so Kyoto Dragonite shows distinctly from Dragonite)
        label = full_name

        for m, lv in (s.get("moves") or {}).items():
            note_move(m, label, "level", lv)
        for m in (s.get("machines") or []):
            note_move(m, label, "tm")
        for m in (s.get("tutor_moves") or []):
            note_move(m, label, "tutor")
        for m in (s.get("egg_moves") or []):
            note_move(m, label, "egg")
        for k, ab in (s.get("abilities") or {}).items():
            if ab:
                note_ability(ab, label)

    # Sort all lists for stable output
    for bucket in move_learners.values():
        bucket["level"].sort(key=lambda t: (t[1], t[0]))
        for k in ("tm", "tutor", "egg"):
            bucket[k] = sorted(set(bucket[k]))
    for ab, lst in ability_learners.items():
        ability_learners[ab] = sorted(set(lst))

    return move_learners, ability_learners


# Map full species name → content slug used in the Pokedex (handles base mapping
# so "Kyoto Dragonite" links to /pokedex/dragonite/, not /pokedex/kyoto-dragonite/).
SPECIES_PAGE_SLUG: dict[str, str] = {}


def build_species_page_slug_map(species_list: list[dict]) -> dict[str, str]:
    """Mirror ingest_pokedex.py's grouping: regional variants share the base
    species' page, so map full names → base content slug."""
    out: dict[str, str] = {}
    for s in species_list:
        full = (s.get("name") or "").strip()
        base, _ = detect_form(full)
        out[full] = content_slug(base)
    return out


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (name or "").lower()).strip("-")


def yaml_string(value) -> str:
    s = "" if value is None else str(value)
    return "'" + s.replace("'", "''") + "'"


def yaml_block_list(items: list, indent: str) -> list[str]:
    """Inline YAML list of quoted strings."""
    if not items:
        return ["[]"]
    return ["[" + ", ".join(yaml_string(x) for x in items) + "]"]


def render_learner_yaml(move_buckets: dict | None, ability_list: list[str] | None,
                         lvl_pairs_max: int = 999) -> list[str]:
    """Emit YAML lines for the learner data (skipped if all empty)."""
    lines: list[str] = []
    if move_buckets:
        lvl_pairs = move_buckets.get("level", []) or []
        if lvl_pairs:
            lines.append("learners_level:")
            for label, lv in lvl_pairs[:lvl_pairs_max]:
                lines.append(f"  - {{ name: {yaml_string(label)}, level: {yaml_string(lv)} }}")
        for src_key, fm_key in (("tm", "learners_tm"), ("tutor", "learners_tutor"), ("egg", "learners_egg")):
            lst = move_buckets.get(src_key, []) or []
            if lst:
                lines.append(f"{fm_key}: " + yaml_block_list(lst, "")[0])
    if ability_list:
        lines.append("learners_ability: " + yaml_block_list(ability_list, "")[0])
    return lines


def render_move_md(record: dict, existing_path: Path | None,
                   move_learners: dict | None = None) -> str:
    name = record.get("name") or ""
    if not name:
        return ""
    type_ = (record.get("type") or "").strip()
    damage_class = (record.get("damage_class") or "").strip()  # physical / special / status
    category_pretty = damage_class.title() if damage_class else ""
    power = record.get("power")
    accuracy = record.get("accuracy")
    pp = record.get("pp")
    priority = record.get("priority")
    target = (record.get("target") or "").replace("_", " ")
    contact = "Yes" if record.get("makes_contact") else "No"
    sound = record.get("sound_based")
    generation = record.get("generation")
    description = (record.get("description") or "").strip()
    healing = record.get("healing")
    drain = record.get("drain")
    min_hits = record.get("min_hits")
    max_hits = record.get("max_hits")
    flinch_chance = record.get("flinch_chance")
    crit_rate = record.get("crit_rate")

    # Status moves have power/accuracy stored as 0/null in some sources — render dashes
    def fmt_num(v, none_ok=True):
        if v is None or v == "":
            return ""
        if v == 0 and none_ok:
            return "—"
        return str(v)

    lines = ["---"]
    lines.append(f"title: {yaml_string(name)}")
    lines.append(f"entry_kind: 'move'")
    lines.append(f"date: {date.today().isoformat()}")
    if type_:
        # Hugo reserves the top-level `type` field for layout selection.
        # Rename to avoid colliding with the engine.
        lines.append(f"move_type: {yaml_string(type_.title())}")
    if category_pretty:
        lines.append(f"category: {yaml_string(category_pretty)}")
    if power is not None:
        lines.append(f"power: {yaml_string(fmt_num(power))}")
    if accuracy is not None:
        # accuracy of 0 in this dataset means "never miss" — render as ∞
        acc = "∞" if accuracy == 0 else str(accuracy)
        lines.append(f"accuracy: {yaml_string(acc)}")
    if pp is not None:
        lines.append(f"pp: {yaml_string(pp)}")
    if priority is not None and priority != 0:
        lines.append(f"priority: {yaml_string(priority)}")
    lines.append(f"contact: {yaml_string(contact)}")
    if generation is not None:
        lines.append(f"generation: {yaml_string('Gen ' + str(generation))}")
    if target:
        lines.append(f"target: {yaml_string(target.title())}")
    if sound:
        lines.append(f"sound_based: 'Yes'")
    if isinstance(min_hits, int) and isinstance(max_hits, int) and (min_hits, max_hits) != (1, 1):
        if min_hits == max_hits:
            lines.append(f"hits: {yaml_string(str(min_hits))}")
        else:
            lines.append(f"hits: {yaml_string(f'{min_hits}–{max_hits}')}")
    if isinstance(flinch_chance, int) and flinch_chance:
        lines.append(f"flinch_chance: {yaml_string(str(flinch_chance) + '%')}")
    if isinstance(crit_rate, int) and crit_rate:
        lines.append(f"crit_rate: {yaml_string('+' + str(crit_rate))}")
    if isinstance(drain, int) and drain:
        sign = "+" if drain > 0 else ""
        lines.append(f"drain: {yaml_string(f'{sign}{drain}%')}")
    if isinstance(healing, int) and healing:
        lines.append(f"healing: {yaml_string(f'{healing}%')}")
    if description:
        lines.append(f"effect: {yaml_string(description)}")
    # Learner data — populated by build_learners() and looked up in main()
    name_key = name
    bucket = (move_learners or {}).get(name_key)
    lines.extend(render_learner_yaml(bucket, None))
    lines.append("---\n")
    return "\n".join(lines) + "\n"


def render_ability_md(record: dict, existing_path: Path | None,
                      ability_learners: dict | None = None) -> str:
    name = record.get("name") or ""
    summary = (record.get("summary") or "").strip()
    if not name:
        return ""
    lines = ["---"]
    lines.append(f"title: {yaml_string(name)}")
    lines.append(f"entry_kind: 'ability'")
    lines.append(f"date: {date.today().isoformat()}")
    if summary:
        lines.append(f"effect: {yaml_string(summary)}")
    ability_list = (ability_learners or {}).get(name)
    lines.extend(render_learner_yaml(None, ability_list))
    lines.append("---\n")
    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--moves", type=Path, default=DEFAULT_MOVES)
    p.add_argument("--abilities", type=Path, default=DEFAULT_ABILITIES)
    p.add_argument("--species", type=Path, default=DEFAULT_SPECIES)
    args = p.parse_args()

    if not args.moves.exists():
        print(f"moves data not found: {args.moves}", file=sys.stderr)
        return 1
    if not args.abilities.exists():
        print(f"abilities data not found: {args.abilities}", file=sys.stderr)
        return 1
    if not MOVES_DIR.exists():
        print(f"content/moves directory not found: {MOVES_DIR}", file=sys.stderr)
        return 1

    moves = json.loads(args.moves.read_text())
    abilities = json.loads(args.abilities.read_text())
    print(f"Loaded {len(moves)} moves, {len(abilities)} abilities from source data.")

    # Build move/ability → learners index from the species data
    move_learners: dict = {}
    ability_learners: dict = {}
    if args.species.exists():
        all_species = json.loads(args.species.read_text())
        species = species_filtered(all_species)
        global SPECIES_PAGE_SLUG
        SPECIES_PAGE_SLUG = build_species_page_slug_map(species)
        move_learners, ability_learners = build_learners(species)
        print(f"Indexed learners across {len(species)} species "
              f"({len(move_learners)} moves with learners, {len(ability_learners)} abilities with learners)")
    else:
        print(f"WARNING: species data not found ({args.species}); learners section will be empty",
              file=sys.stderr)

    # Build slug -> existing path lookup so we can match by slug
    existing = {p.stem: p for p in MOVES_DIR.glob("*.md") if p.name != "_index.md"}

    populated = 0
    skipped = 0
    new_files = 0
    name_collisions: list[str] = []
    seen_slugs: set[str] = set()

    for source_name, recs, render_fn, learners_arg in [
        ("moves", moves, render_move_md, move_learners),
        ("abilities", abilities, render_ability_md, ability_learners),
    ]:
        for rec in recs:
            slug = slugify(rec.get("name", ""))
            if not slug:
                skipped += 1
                continue
            if slug in seen_slugs:
                name_collisions.append(rec.get("name", "?"))
                continue
            seen_slugs.add(slug)
            target = existing.get(slug, MOVES_DIR / f"{slug}.md")
            md = render_fn(rec, target if target.exists() else None, learners_arg)
            if not md:
                skipped += 1
                continue
            if not target.exists():
                new_files += 1
            target.write_text(md, encoding="utf-8")
            populated += 1

    print(f"Populated {populated} pages ({new_files} new, {populated - new_files} updated)")
    if skipped:
        print(f"Skipped {skipped} entries (missing name or empty)")
    if name_collisions:
        print(f"Name collisions across moves+abilities (skipped): {len(name_collisions)}")
        for n in name_collisions[:10]:
            print(f"  {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
